server:
  port: 8080

spring:
  application:
    name: dentist-plus-backend
  
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://mongo-db:27017/dentistplus}
      database: ${MONGODB_DATABASE:dentistplus}
  
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.dentistplus: DEBUG
    org.springframework.data.mongodb: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  show-actuator: true